
import { authOptions } from "@/app/api/auth/auth.options";
import AuthSignIn from "@/components/auth/auth.sigin";
import { getServerSession } from "next-auth/next";
import { redirect } from 'next/navigation';

export const metadata = {
    title: "Sign in",
    description: "Generated by Next.js",
}


const SignInPage = async () => {
    const session = await getServerSession(authOptions);
    if (session) {
        //redirect to homepage
        redirect("/");
    }

    return (
        <>
            <AuthSignIn />
        </>
    )
}

export default SignInPage;
