
import { sendRequest } from "@/utils/api";
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import ProfileTrack from "@/components/header/profile.tracks";
import { Container, Divider } from "@mui/material";
import { isMobileDevice } from "@/lib/responsive";
import CategoryTrack from "@/components/category/category.track";
export const metadata = {
    title: "Profile",
    description: "Generated by Next.js",
}
const ProfilePage = async ({ params }: { params: { slug: string } }) => {
    const mobile = isMobileDevice(); // execute the function
    const tracks = await sendRequest<IBackendRes<IModelPaginate<ITrackTop>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/tracks/users?current=1&pageSize=10`,
        method: "POST",
        body: {
            id: params.slug,
        },
        nextOption: {
            // cache: "no-store" ,
            next: { tags: ['track-by-profile'] }
        }
    });
    return (
        <>
            <Container sx={{ marginTop: "40px" }}>
                <div style={{ fontSize: "18px", color: "#999" }}>Your track uploaded</div>
                <Divider sx={{ margin: "20px 0" }} />
                <Box sx={{ flexGrow: 1, }}>
                    {mobile ?
                        <CategoryTrack data={tracks?.data?.result} />
                        :
                        <Grid container spacing={{ xs: 2, md: 3 }} columns={{ xs: 4, sm: 8, md: 12 }}>
                            {tracks?.data && tracks?.data?.result.map((item, index) => {
                                return (
                                    <Grid item xs={6} key={index}>
                                        <ProfileTrack data={item} />
                                    </Grid>
                                )
                            })}
                        </Grid>
                    }
                </Box>
            </Container>
        </>
    )
}

export default ProfilePage;