
import AppHeader from '@/components/header/app.header';
import ThemeRegistry from '@/components/theme-registry/theme.registry';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import AppFooter from '@/components/footer/app.footer';
import { SessionProvider } from "next-auth/react";
import NextAuthWrapper from '@/lib/next.auth.wrapper';

export const metadata = {
  title: "Next.js Duy Nguyễn",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <NextAuthWrapper>
            {children}
          </NextAuthWrapper>
        </ThemeRegistry>
      </body>
    </html>
  );
}
