services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80

  backend-soundcloud:
    image: harypham97/hoidanit-backend-soundcloud-public:1.0
    environment:
      PORT: 8001
      MONGO_URL: mongodb+srv://duy2k4ml1234:10120045z@cluster0.glah44h.mongodb.net/nextjs
    ports:
      - 8001:8001

  frontend-nextjs:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped

#docker compose -p hoidanit-soundcloud up -d
