
import AppHeader from '@/components/header/app.header';
import ThemeRegistry from '@/components/theme-registry/theme.registry';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import AppFooter from '@/components/footer/app.footer';

export const metadata = {
  title: "Next.js Duy Nguyễn",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <AppHeader />
      {children}
      <div style={{ marginBottom: "100px" }}></div>
      <AppFooter />
    </>
  );
}
